[project]
title = "Netflix Titles Dashboard"
version = "0.1.0"
port = 8501
slug = "netflix-titles-dashboard"
entrypoint = "dashboard.py"

[branding]
name = "Netflix Dashboard"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.netflix_titles]
type = "csv"
path = "/Users/suryadeipreddy/Downloads/SL Assesment/preswald/netflix_titles.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"